# These are supported funding model platforms

github: mrz1836
custom: https://mrz1818.com/?tab=tips&utm_source=github&utm_medium=sponsor-link&utm_campaign=go-meta-extractor&utm_term=go-meta-extractor&utm_content=go-meta-extractor
